# Generated by Django 5.1.4 on 2024-12-29 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_task',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
