# Generated by Django 5.1.3 on 2025-02-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_add_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_task',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
