# Generated by Django 5.1.3 on 2025-02-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_add_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_task',
            name='duration',
        ),
    ]
